name: Build and deploy Node.js app to Azure Web App - BahasaKitani

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'  # Adjust to the Node.js version your app uses

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build --if-present

      - name: Test project
        run: npm run test --if-present

      - name: Prepare artifact for deployment
        run: |
          mkdir deploy
          cp -R * deploy
          cd deploy
          npm install --production

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'BahasaKitani'  # Replace with your actual web app name
          package: './node-app'     # Ensure this path matches your artifact
